# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ariel Elkin
email: arielelkin@gmail.com
description: The website of Ariel Elkin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arielelkin.github.io" # the base hostname & protocol for your site
twitter_username: AriVocals
github_username:  arielelkin
disqus: arielelkin

# Build settings
markdown: kramdown
